### ISSUE TITLE
CSS scroll snap isn't working

### ISSUE THREAD

**Issue by deodat** [oberonamsterdam/horizontal#15]
Hello,

I tried to implement css scroll snaps but it seems to come into conflict with your script : when I try to scroll, my sections with scroll-snap implemented shake a lot and it's visually awful.

Do you know how I could avoid this ?

Thanks a lot !

**Comment by kheiraoudejans** [comment]
Hello @deodat!

Can you share your code? 

Thanks in advance!

**Comment by deodat** [comment]
Hello @kheiraoudejans !

It's on a protected staging website but I can summarize it like this :

JS :
```
import HorizontalScroll from '../../node_modules/@oberon-amsterdam/horizontal';

const content = document.querySelector('.site-content');
const horizontal = new HorizontalScroll({ container: content });
```

HTML :
```
<div id="content" class="site-content">
    <section class="section">
    </section>
    <section class="section">
    </section>
    <section class="section">
    </section>
</div>
```

CSS :
```
.site-content {
        display: flex;
        height: 100%;
       position: relative;
       scroll-snap-type: x mandatory;

        > .section {
            height: 100%;
            scroll-snap-align: start;
        }
}
```

**Comment by tlorent** [comment]
Hi @deodat,

Thank you for sharing your code. We will look into your issue and report back as soon as we have found a solution.

Thank you for your patience!

**Comment by tlorent** [comment]
Hi @deodat ,

We haven taken some time to investigate your issue and we are wondering what you are trying to implement UI-wise? Based on your code we see that you have a full-height container with full-height sections that you want to scroll-snap. These sections should also be wide enough for `overflow` to occur (otherwise scroll-snap would not really make a lot of sense) then you would need `overflow-x: scroll` (or another value like `auto`) set on the `div` with the `site-content` class.

Please have a look at this [CSS-tricks article about scroll-snapping for more information](https://css-tricks.com/practical-css-scroll-snapping/#example-4-horizontal-full-screen).

If it still is not working, please let us know.
